name: TownyReputation
main: me.bigjaymalcolm.townyreputation.Main
version: 0.1
author: BigJayMalcolm
depend: [ Towny ]
commands:
   getreputation:
     aliases: [getrep]
   setreputation:
     aliases: [setrep]