name: TownyReputation
main: me.bigjaymalcolm.townyreputation.Main
version: 0.1
author: BigJayMalcolm
depend: [ Towny ]
commands:
   getreputation:
     aliases: [getrep]
     description: Check the reputation you have towards a specific town/nation.
     usage: /<command> [town/nation]
   setreputation:
     aliases: [setrep]
     description: Set a player's reputation towards a specific town/nation.
     usage: /<command> [player name] [town/nation] [value]
     permission: <plugin name>.admin
     permission-message: You don't have <permission>